In [141]:
import pandas as pd, numpy as np,os

In [142]:
processed_data_path=os.path.join(os.path.pardir,'data','processed')
processed_df_path=os.path.join(processed_data_path,'Absenteeism_processed.csv')

In [143]:
df=pd.read_csv(processed_df_path,index_col=0)

In [144]:
df.head()

Reason for absence_1  Reason for absence_2  Reason for absence_3  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     1                     0                     0   
4                     0                     0                     0   

   Reason for absence_4  Month of absence  Day of the week  Seasons  \
0                     1                 7                3        1   
1                     0                 7                3        1   
2                     1                 7                4        1   
3                     0                 7                5        1   
4                     1                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  \
0                   289.0                             36.0          13.0   
1                   118.0                             13.0          18.0   
2                   179.0                             51.0          18.0   
3                   279.0                              5.0          14.0   
4                   289.0                             36.0          13.0   

   Work load Average/day   Hit target  Son  Social drinker      Height  \
0                 239.554        97.0    1             1.0  172.000000   
1                 239.554        97.0    0             1.0  172.000009   
2                 239.554        97.0    0             1.0  170.000000   
3                 239.554        97.0    1             1.0  168.000000   
4                 239.554        97.0    1             1.0  172.000000   

   Body mass index  Absenteeism time in hours  
0             30.0                        4.0  
1             31.0                        0.0  
2             31.0                        2.0  
3             24.0                        4.0  
4             30.0                        2.0

Lets convert the prediction problem to a logistic regression problem where we will classify if employee absenteeism is normal or excessive.

In [145]:
df['Absenteeism Class']=np.where(df['Absenteeism time in hours']>df['Absenteeism time in hours'].median(),1,0)

In [146]:
df.drop(['Absenteeism time in hours'],axis=1,inplace=True)

In [147]:
df.head()

Reason for absence_1  Reason for absence_2  Reason for absence_3  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     1                     0                     0   
4                     0                     0                     0   

   Reason for absence_4  Month of absence  Day of the week  Seasons  \
0                     1                 7                3        1   
1                     0                 7                3        1   
2                     1                 7                4        1   
3                     0                 7                5        1   
4                     1                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  \
0                   289.0                             36.0          13.0   
1                   118.0                             13.0          18.0   
2                   179.0                             51.0          18.0   
3                   279.0                              5.0          14.0   
4                   289.0                             36.0          13.0   

   Work load Average/day   Hit target  Son  Social drinker      Height  \
0                 239.554        97.0    1             1.0  172.000000   
1                 239.554        97.0    0             1.0  172.000009   
2                 239.554        97.0    0             1.0  170.000000   
3                 239.554        97.0    1             1.0  168.000000   
4                 239.554        97.0    1             1.0  172.000000   

   Body mass index  Absenteeism Class  
0             30.0                  1  
1             31.0                  0  
2             31.0                  0  
3             24.0                  1  
4             30.0                  0

In [149]:
num_col=['Transportation expense', 'Distance from Residence to Work',
                   'Service time', 'Work load Average/day ', 'Hit target','Height', 'Body mass index']

In [150]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df_scaled=df.copy()
df_scaled[num_col]=scaler.fit_transform(df_scaled[num_col])
# X_scaled=X
# scaler.fit(X[:,[7,8,9,10,11,14,15]])
# X_scaled[:,[7,8,9,10,11,14,15]]=scaler.transform(X[:,[7,8,9,10,11,14,15]])

In [152]:
X=df_scaled.iloc[:,:-1].values
y=df_scaled.iloc[:,-1].values

In [153]:
df_scaled

Reason for absence_1  Reason for absence_2  Reason for absence_3  \
0                       0                     0                     0   
1                       0                     0                     0   
2                       0                     0                     0   
3                       1                     0                     0   
4                       0                     0                     0   
5                       0                     0                     0   
6                       0                     0                     0   
7                       0                     0                     0   
8                       0                     0                     1   
9                       0                     0                     0   
10                      1                     0                     0   
11                      1                     0                     0   
12                      1                     0                     0   
13                      1                     0                     0   
14                      0                     0                     0   
15                      1                     0                     0   
16                      0                     0                     0   
17                      0                     0                     1   
18                      1                     0                     0   
19                      0                     0                     0   
20                      1                     0                     0   
21                      1                     0                     0   
22                      1                     0                     0   
23                      0                     0                     0   
24                      0                     1                     0   
25                      0                     0                     0   
26                      0                     0                     0   
27                      0                     0                     0   
28                      0                     1                     0   
29                      0                     0                     0   
..                    ...                   ...                   ...   
707                     0                     0                     0   
708                     0                     0                     0   
709                     1                     0                     0   
710                     0                     0                     0   
711                     0                     0                     1   
712                     0                     0                     1   
713                     0                     0                     0   
714                     0                     0                     0   
715                     0                     0                     0   
716                     0                     0                     1   
717                     1                     0                     0   
718                     0                     0                     0   
719                     1                     0                     0   
720                     0                     0                     0   
721                     0                     0                     0   
722                     1                     0                     0   
723                     1                     0                     0   
724                     0                     0                     0   
725                     0                     0                     0   
726                     0                     0                     1   
727                     1                     0                     0   
728                     0                     0                     0   
729                     1                     0                

In [154]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=0)

In [155]:
X_test.shape

(148, 16)

In [156]:
from sklearn.linear_model import LogisticRegression


In [157]:
logit=LogisticRegression()
logit.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [158]:
logit.score(X_train,y_train)

0.7385398981324278

In [159]:
logit.score(X_test,y_test)

0.777027027027027

Lets look at the intercept and coefficients of the model

In [160]:
logit.intercept_

array([-0.91697641])

In [161]:
logit.coef_

array([[ 2.18789311,  1.95207458,  2.07277999,  0.62039073,  0.04807646,
        -0.08154004, -0.34185613,  0.52955715, -0.0794636 , -0.02714478,
         0.08941637, -0.10183254,  0.62221902,  0.40359874,  0.11107644,
         0.06070335]])

In [162]:
summary=pd.DataFrame(columns=df.columns[:-1],data=logit.coef_)

In [163]:
summary=summary.reset_index()

In [164]:
summary.columns=['Intercept', 'Reason for absence_1', 'Reason for absence_2',
       'Reason for absence_3', 'Reason for absence_4', 'Month of absence',
       'Day of the week', 'Seasons', 'Transportation expense',
       'Distance from Residence to Work', 'Service time',
       'Work load Average/day ', 'Hit target', 'Son', 'Social drinker',
       'Height', 'Body mass index']

In [165]:
summary.Intercept=logit.intercept_

In [166]:
s=summary.T

In [167]:
s.columns=['Coefficient']

In [168]:
s.sort_values('Coefficient')

Coefficient
Intercept                          -0.916976
Seasons                            -0.341856
Hit target                         -0.101833
Day of the week                    -0.081540
Distance from Residence to Work    -0.079464
Service time                       -0.027145
Month of absence                    0.048076
Body mass index                     0.060703
Work load Average/day               0.089416
Height                              0.111076
Social drinker                      0.403599
Transportation expense              0.529557
Reason for absence_4                0.620391
Son                                 0.622219
Reason for absence_2                1.952075
Reason for absence_3                2.072780
Reason for absence_1                2.187893

In [169]:
s['Odds Ratio']=np.exp(s['Coefficient'])

In [170]:
s

Coefficient  Odds Ratio
Intercept                          -0.916976    0.399726
Reason for absence_1                2.187893    8.916407
Reason for absence_2                1.952075    7.043284
Reason for absence_3                2.072780    7.946885
Reason for absence_4                0.620391    1.859655
Month of absence                    0.048076    1.049251
Day of the week                    -0.081540    0.921696
Seasons                            -0.341856    0.710450
Transportation expense              0.529557    1.698180
Distance from Residence to Work    -0.079464    0.923612
Service time                       -0.027145    0.973220
Work load Average/day               0.089416    1.093536
Hit target                         -0.101833    0.903181
Son                                 0.622219    1.863058
Social drinker                      0.403599    1.497203
Height                              0.111076    1.117480
Body mass index                     0.060703    1.062584

In [171]:
import pickle

In [172]:
with open('logit_model','wb') as file:
    pickle.dump(logit,file)

In [173]:
with open('scaler','wb') as file:
    pickle.dump(scalar,file)

In [134]:
logit.predict_proba(X_test)[:,1]

array([0.29740603, 0.68600782, 0.30852583, 0.64726361, 0.14023534,
       0.59356612, 0.15243926, 0.73123817, 0.64300942, 0.32571407,
       0.26564662, 0.37536038, 0.09318465, 0.61957939, 0.37534621,
       0.48568067, 0.7315221 , 0.66072506, 0.27545483, 0.35716205,
       0.67436741, 0.54916772, 0.58478894, 0.7467189 , 0.184622  ,
       0.30042358, 0.60217457, 0.89743877, 0.71900995, 0.12942753,
       0.81797571, 0.84278025, 0.40347251, 0.59906362, 0.88247991,
       0.30434563, 0.16322905, 0.37828739, 0.75873031, 0.19227132,
       0.67181771, 0.18003694, 0.94124551, 0.32341215, 0.31507513,
       0.21548065, 0.20345061, 0.66268927, 0.37807491, 0.7505874 ,
       0.1617597 , 0.24794683, 0.62139442, 0.57064971, 0.58097373,
       0.71139101, 0.75839824, 0.65677523, 0.73063605, 0.55529569,
       0.80828301, 0.1931698 , 0.19745616, 0.23522518, 0.58142806,
       0.91260728, 0.58490044, 0.3240031 , 0.46260226, 0.35402655,
       0.64872428, 0.8293622 , 0.33942712, 0.71266974, 0.35396

In [174]:
from sklearn.externals import joblib
joblib.dump(logit,r'model.pickle')
joblib.dump(scaler,r'scaler.pickle')

['scaler.pickle']

In [184]:
import pandas as pd, numpy as np,os
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,roc_curve
from sklearn.externals import joblib
def load_data():
    processed_data_path=os.path.join(os.path.pardir,'data','processed')
    processed_df_path=os.path.join(processed_data_path,'Absenteeism_processed.csv')
    df=pd.read_csv(processed_df_path,index_col=0)
    return df
def convert_to_class(df):
    df['Absenteeism Class']=np.where(df['Absenteeism time in hours']>df['Absenteeism time in hours'].median(),1,0)
    df.drop(['Absenteeism time in hours'],axis=1,inplace=True)
    return df
def scale_data(df):
    num_col=['Transportation expense', 'Distance from Residence to Work',
                       'Service time', 'Work load Average/day ', 'Hit target','Height', 'Body mass index']
    scaler=StandardScaler()
    df_scaled=df.copy()
    df_scaled[num_col]=scaler.fit_transform(df_scaled[num_col])
    return df_scaled,scaler
def split_data(df):
    X=df.iloc[:,:-1].values
    y=df.iloc[:,-1].values
    return train_test_split(X,y,test_size=0.2,random_state=0)
def train_model(X_train,y_train):
    logit=LogisticRegression()
    logit.fit(X_train,y_train)
    return logit
def model_preformance(model,X_train,X_test,y_train,y_test):
    print('Accuracy for Train Data',accuracy_score(y_train,model.predict(X_train)))
    print('Accuracy for Test Data',accuracy_score(y_test,model.predict(X_test)))
    print('Precision Score',precision_score(y_test,model.predict(X_test)))
    print('Recall Score',recall_score(y_test,model.predict(X_test)))
    print('Confusion Matrix',confusion_matrix(y_test,model.predict(X_test)))
def model_summary(model,df):
    summary=pd.DataFrame(columns=df.columns[:-1],data=logit.coef_)
    summary=summary.reset_index()
    summary.columns=['Intercept', 'Reason for absence_1', 'Reason for absence_2',
           'Reason for absence_3', 'Reason for absence_4', 'Month of absence',
           'Day of the week', 'Seasons', 'Transportation expense',
           'Distance from Residence to Work', 'Service time',
           'Work load Average/day ', 'Hit target', 'Son', 'Social drinker',
           'Height', 'Body mass index']
    summary.Intercept=logit.intercept_
    s=summary.T
    s.columns=['Coefficient']
    s.sort_values('Coefficient')
    s['Odds Ratio']=np.exp(s['Coefficient'])
    print(s)
def persist_model(model,scaler):
    joblib.dump(model,r'model.pickle')
    joblib.dump(scaler,r'scaler.pickle')

if __name__=='__main__':
    df=load_data()
    df=convert_to_class(df)
    df,scaler=scale_data(df)
    X_train,X_test,y_train,y_test=split_data(df)
    model=train_model(X_train,y_train)
    model_summary(model,df)
    model_preformance(model,X_train,X_test,y_train,y_test)
    persist_model(model,scaler)

                                 Coefficient  Odds Ratio
Intercept                          -0.916976    0.399726
Reason for absence_1                2.187893    8.916407
Reason for absence_2                1.952075    7.043284
Reason for absence_3                2.072780    7.946885
Reason for absence_4                0.620391    1.859655
Month of absence                    0.048076    1.049251
Day of the week                    -0.081540    0.921696
Seasons                            -0.341856    0.710450
Transportation expense              0.529557    1.698180
Distance from Residence to Work    -0.079464    0.923612
Service time                       -0.027145    0.973220
Work load Average/day               0.089416    1.093536
Hit target                         -0.101833    0.903181
Son                                 0.622219    1.863058
Social drinker                      0.403599    1.497203
Height                              0.111076    1.117480
Body mass index                

In [177]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,roc_curve

In [178]:
accuracy_score(y_test,model.predict(X_test))

0.777027027027027

In [179]:
precision_score(y_test,model.predict(X_test))

0.796875

In [180]:
recall_score(y_test,model.predict(X_test))

0.7183098591549296

In [181]:
roc_curve(y_test,model.predict(X_test))

(array([0.        , 0.16883117, 1.        ]),
 array([0.        , 0.71830986, 1.        ]),
 array([2, 1, 0]))

In [182]:
confusion_matrix(y_test,model.predict(X_test))

array([[64, 13],
       [20, 51]], dtype=int64)